### ISSUE TITLE
The command `yarn start:ios` fails with `Unable to resolve module aws-sdk` error

### ISSUE THREAD

**Issue by trivikr** [aws-samples/aws-sdk-js-tests#113]
## Describe the bug
The command `yarn start:ios` fails with `Unable to resolve module aws-sdk` error

## Steps to reproduce
Follow README, and run `yarn start:ios`

```console
$ node -v
v16.16.0
```

#### Observed behavior
The following error is thrown in console

```console
 BUNDLE  ./index.js 

error: Error: Unable to resolve module aws-sdk from /Users/trivikr/workspace/aws-sdk-js-tests/packages/utils/src/utils.js: aws-sdk could not be found within the project or in these directories:
  ../../node_modules
  ../../../node_modules
  /Users/trivikr/workspace/aws-sdk-js-tests/packages/react-native/node_modules/aws-sdk
> 1 | import AWS from "aws-sdk";
    |                  ^
  2 | 
  3 | import { fromCognitoIdentityPool } from "@aws-sdk/credential-provider-cognito-identity";
  4 | import { CognitoIdentityClient } from "@aws-sdk/client-cognito-identity";
    at ModuleResolver.resolveDependency (/Users/trivikr/workspace/aws-sdk-js-tests/packages/react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/Users/trivikr/workspace/aws-sdk-js-tests/packages/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/trivikr/workspace/aws-sdk-js-tests/packages/react-native/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/trivikr/workspace/aws-sdk-js-tests/packages/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/trivikr/workspace/aws-sdk-js-tests/packages/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/trivikr/workspace/aws-sdk-js-tests/packages/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/trivikr/workspace/aws-sdk-js-tests/packages/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/trivikr/workspace/aws-sdk-js-tests/packages/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 1)
```

#### Expected behavior
The bundling of the react-native doesn't fail, and it provides options to make v2/v3 calls.

#### Screenshots

<details>
<summary>Screenshot</summary>

![unable-to-resolve-module](https://user-images.githubusercontent.com/16024985/182644652-77ca841e-0b0d-42d6-a8ef-d2f7e17ebfbf.png)

</details>

## Additional context
react-native was updated in https://github.com/aws-samples/aws-sdk-js-tests/pull/105

**Comment by trivikr** [comment]
Possibly related to yarn bump to v3.2.1 in https://github.com/aws-samples/aws-sdk-js-tests/pull/106

The code changes tested in react-native bump to v0.69.1 works.

<details>
<summary>Screenshot</summary>

![pr-105](https://user-images.githubusercontent.com/16024985/182648098-e59ba082-4df3-4062-8cbf-f65784b647ac.png)


</details>

**Comment by trivikr** [comment]
Verified that the issue was introduced in https://github.com/aws-samples/aws-sdk-js-tests/commit/633d31566e00c178468c72c6548638931b606a1d

<details>
<summary>Screenshot</summary>

![yarn-3 2 1-screenshot](https://user-images.githubusercontent.com/16024985/182657619-03325630-8fb7-4453-89c7-5151bac8bb85.png)


</details>
